#!/bin/bash

WDAY=$(date +%u)
HOUR=$(date +%-H)

if [[ $WDAY > 5 ]]; then
  WALLPAPER="$HOME/media/pictures/wallpapers/weekend.jpg"
elif [[ $HOUR -gt 5 && $HOUR -lt 14 ]]; then
  WALLPAPER="$HOME/media/pictures/wallpapers/morning.jpg"
elif [[ $HOUR -gt 13 && $HOUR -lt 22 ]]; then
  WALLPAPER="$HOME/media/pictures/wallpapers/afternoon.jpg"
else
  WALLPAPER="$HOME/media/pictures/wallpapers/night.jpg"
fi

feh --no-xinerama --bg-fill $WALLPAPER
