#!/usr/bin/env python
# encoding: utf-8

import fileinput

def group_lines(diff_lines):
    added_lines = []
    removed_lines = []
    for line in diff_lines:
        if line.startswith('+') and not line.startswith('+++'):
            added_lines.append(line)
        elif line.startswith('-') and not line.startswith('---'):
            removed_lines.append(line)
    return added_lines, removed_lines

def main(diff_lines):
    added_lines, removed_lines = group_lines(diff_lines)
    print("%i lines of diff" % len(diff_lines))
    print("%i lines added" % len(added_lines))
    print("%i lines removed" % len(removed_lines))
    print("%i lines net change" % (len(added_lines) - len(removed_lines)))

if __name__ == '__main__':
    main(list(fileinput.input()))
