#!/usr/bin/env python

import os, sys, time

if len(sys.argv) != 2:
    sys.exit("Usage: %s interface" % sys.argv[0])
if not os.path.exists("/sys/class/net/%s" % sys.argv[1]):
    sys.exit("Error: Interface not found.")
iface = sys.argv[1]

rx = open("/sys/class/net/%s/statistics/rx_bytes" % iface)
tx = open("/sys/class/net/%s/statistics/tx_bytes" % iface)
curr = (int(rx.read()), int(tx.read()))
kbps = [0, 0]

while True:
    rx.seek(0)
    tx.seek(0)

    prev, curr = curr, (int(rx.read()), int(tx.read()))
    kbps[0] = (curr[0] - prev[0]) / 1024
    kbps[1] = (curr[1] - prev[1]) / 1024

    sys.stdout.write("%.2fK / %.2fK\n".ljust(6) % (kbps[0], kbps[1]))
    sys.stdout.flush()
    time.sleep(1)
