#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# check if HDMI connected and set output to it
xrandr | grep HDMI1 | grep " connected"
[[ $? -eq 0 ]] && xrandr --output HDMI1 --primary --auto --output LVDS1 --off

/usr/bin/xbmc-standalone
