#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# check if HDMI connected and set output to it
xrandr | grep HDMI1 | grep " connected"
[[ $? -eq 0 ]] && xrandr --output HDMI1 --primary --auto --output LVDS1 --off

# check if VGA1 connected adn set output to it
xrandr | grep VGA1 | grep -v "disconnected"
[[ $? -eq 0 ]] && xrandr --output VGA1 --primary --auto --output LVDS1 --off

# start devmon daemon
[[ -z $(pgrep -af devmon)     ]] && /usr/bin/devmon > /dev/null 2> /dev/null &
[[ -z $(pgrep -af pulseaudio) ]] && /usr/bin/start-pulseaudio-x11 &

/usr/bin/xbmc-standalone
