# ~/.tmuxinator/default.yml

name: default
root: ~/

windows:
  - sys:
      layout: even-vertical
      panes:
        - htop
        - clear && syu
        - sudo journalctl -fn60
  - net:
      layout: main-horizontal
      panes:
        - irssi
        - rtorrent
        - mutt
  - music:
      layout: main-vertical
      panes:
        - ncmpcpp
        - cd media/music && clear && ls
        - alsamixer
