font:
  normal:
    family: Monofur Nerd Font
  bold:
    family: Monofurbold Nerd Font
  italic:
    family: Monofuritalic Nerd Font
  size: 17

window:
  padding:
    x: 17
    y: 17

cursor:
  style:
    shape:    Block
    blinking: Never

draw_bold_text_with_bright_colors: true
