font:
  normal:
    family: Monofur Nerd Font
    style: Regular
  bold:
    family: Monofur Nerd Font
    style: Bold
  italic:
    family: Monofur Nerd Font
    style: Italic
  size: 17

window:
  padding:
    x: 17
    y: 17

cursor:
  style:
    shape:    Block
    blinking: Never

draw_bold_text_with_bright_colors: true
